import React, {useState, useEffect, useRef} from 'react'
import PropTypes from 'prop-types';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Lottie from "lottie-react";
import cursor1 from "../assets/cursors/mouse-click-pointer-cursor-arrow-sign.json";

import Box from '@mui/material/Box';
import Grid from '@mui/material/Unstable_Grid2';
import Tooltip from '@mui/material/Tooltip';
import { styled } from '@mui/system';

import NFTMetadata from "../data/sampleNFTData.json"



const MDHGrid: NextPage = ({draw, height, width}: any) => {
  const [position, setPosition] = useState({ x: undefined, y: undefined });
  const canvas = useRef(); // ADDED

  const StyledTooltip = styled(Tooltip)({
    tooltipPlacementTop: {
      margin: "4px 0",
      transform: "scale(2)"
    },
  });

  React.useEffect(() => {
    // @ts-ignore
    const context = canvas.current.getContext('2d');
    // @ts-ignore
    draw(context);
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <StyledTooltip 
              title="Delete" 
              followCursor
            >
          <h1 className={styles.title}>
            Welcome to MillionDollarHomepage
          </h1>
        </StyledTooltip>
        <div>
        </div>

      <div>
        <h3>hello</h3>
      </div>
      <canvas
        // @ts-ignore
        ref={canvas}
        width="500"
        height="500"
        style={{
          border: "1px solid grey"
        }}
      />

    </div>
  )
}

MDHGrid.propTypes = {
  draw: PropTypes.func.isRequired,
  height: PropTypes.number.isRequired, 
  width: PropTypes.number.isRequired, 
};

export default MDHGrid
